export default {
    introTitle1: "Welcome to BloodConnect!",
    introTitle2: "Browse through requests",
    introTitle3: "Give to those who need it the most",
    introDescription1: "BloodConnect is a platform that connects blood donor and donee.\n\nOh, it's free and non-profit!",
    introDescription2: "Feeling generous? Browse through blood requests and start donating.\n\nNeed blood? Make a request and near users will be notified.",
    introDescription3: "BloodConnect aims to find blood donors fast in cases of emergency and ensure healthy supply of blood in blood banks.",

    startConnecting: "Start connecting",

    logIntoYourAccount: "Log into your account",
    fullName: "Full Name",
    email: "Email",
    password: "Password",
    forgotPassword: "Forgot password?",
    logIn: "Log in",
    signInWithGoogle: "Sign in with Google",
    createANewAccount: "Create a new account",
    joinUs: "Join us",
    logInAsGuest: "Log in as guest",

    explore: "Explore",
    requests: "Requests",
    searchAnythingHere: "Search anything here",
    searchHere: "Search here",
    noRequests: "No requests here.",

    next: "Next",
    cancel: "Cancel",
    submit: "Submit",

    makeARequest: "Make a request for...",
    blood: "Blood",
    platelets: "Platelets",
    plasma: "Plasma",
    forWhichBloodType: "For which blood type?",
    choose: "Choose",
    howManyUnits: "How many units are required?",
    howCanDonorContact: "How can the donor contact you?",
    contactName: "Contact name",
    useYourName: "Use your name",
    contactNumber: "Contact number",
    contactDisclaimer: "This information is...",
    anythingDonorShouldKnow: "Anything the donors should know?",
    shareStory: "Share a story?",
    thisIsAnEmergency: "This is an emergency",
    emergencyDescription: "BloodConnect will prioritise this request to help find donors faster. Please be responsible and only tick if you need donation urgently.",
    charactersAllowed: "characters allowed",
    chooseBloodType: "Choose a blood type",
    pickYourLocation: "Pick your location",

    reviewYourRequest: "Review your request",
    requestDetails: "Request details",
    requestingFor: "Requesting for",
    bloodType: "Blood type",
    numberOfUnits: "Number of units",
    contactDetails: "Contact details",
    appointmentDetails: "Appointment details",
    additionalDetails: "Additional details",

    allDone: "All done!",
    requestMadeText: "We have submitted your request, and a donor will contact you soon. Hang in there!",

    fillYourParticulars: "Fill your particulars",
    whatsYourBloodType: "What's your blood type?",
    whatsYourName: "What's your name?",
    howCanRequesterContact: "How can the requester contact you?",
    returnHome: "Return home",
    thanks: "Thanks!",
    donationMadeText: "We have submitted your availability, and the requester will contact you soon. Thanks!",
    requestCompleted: "Thank you for using BloodConnect! This request will be closed.",
    whoops: "Whoops!",
    requestWasCompleted: "This request has been closed. Thank you for your kind intentions. Search for other requests?",

    myRequests: "My requests",
};